export const ACTION_TYPES = {
    UPDATE_USERS: 'UPDATE_USERS',
    UPDATE_USERS_FAILED: 'UPDATE_USERS_FAILED',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    UPDATE_USER_INFO_FAILED: 'UPDATE_USER_INFO_FAILED',
    TOGGLE_SPINNER: 'TOGGLE_SPINNER',
};